import type { Task, TaskEvent } from '../../app/lib/types'

const ago = (mins: number) => new Date(Date.now() - mins * 60000).toISOString()

export const mockTasks: Task[] = [
  {
    id: 'task-001-auth-refactor',
    userId: 1,
    mode: 'implement',
    status: 'running',
    internalStatus: 'progress',
    branch: 'feature/auth-refactor',
    repoPath: '/app',
    createdAt: ago(30),
    updatedAt: ago(2),
    message: 'Claude subprocess spawned',
    meta: { stepIndex: 2, stepTotal: 4 },
  },
  {
    id: 'task-002-db-migration',
    userId: 1,
    mode: 'implement',
    status: 'needs_input',
    internalStatus: 'needs_input',
    branch: 'feature/db-migration',
    repoPath: '/app',
    createdAt: ago(60),
    updatedAt: ago(15),
    message: 'Waiting for user input',
    meta: {},
    question: 'Which database engine should be used?',
    options: ['PostgreSQL', 'SQLite', 'MySQL'],
    needsInputAt: ago(15),
  },
  {
    id: 'task-002b-env-config',
    userId: 1,
    mode: 'implement',
    status: 'needs_input',
    internalStatus: 'needs_input',
    branch: 'feature/env-config',
    repoPath: '/app',
    createdAt: ago(45),
    updatedAt: ago(10),
    message: 'Waiting for user input',
    meta: {},
    question: 'Where should the config file be stored?',
    options: null,
    needsInputAt: ago(10),
  },
  {
    id: 'task-003-api-review',
    userId: 1,
    mode: 'review',
    status: 'review_pass',
    internalStatus: 'review_pass',
    branch: 'feature/api-endpoints',
    repoPath: '/app',
    createdAt: ago(120),
    updatedAt: ago(90),
    message: 'Review passed',
    meta: { reviewVerdict: 'pass' },
  },
  {
    id: 'task-004-ui-review',
    userId: 1,
    mode: 'review',
    status: 'review_fail',
    internalStatus: 'review_fail',
    branch: 'feature/ui-components',
    repoPath: '/app',
    createdAt: ago(45),
    updatedAt: ago(40),
    message: 'Review failed — 2 findings',
    meta: { reviewIteration: 1, reviewMaxIterations: 3 },
    reviewFindings: 'Missing error handling in form submission. XSS vulnerability in user display name.',
    structuredFindings: [
      { id: 'F1', severity: 'major', file: 'src/components/Form.vue', issue: 'No error handling on submit', risk: 'Silent failures', required_fix: 'Add try/catch with user feedback', acceptance_check: 'Error toast shown on failure' },
      { id: 'F2', severity: 'critical', file: 'src/components/UserName.vue', issue: 'XSS via display name', risk: 'Script injection', required_fix: 'Sanitize output', acceptance_check: 'HTML entities escaped' },
    ],
  },
  {
    id: 'task-005-perf',
    userId: 1,
    mode: 'implement',
    status: 'completed',
    internalStatus: 'completed',
    branch: 'feature/perf-optimization',
    repoPath: '/app',
    createdAt: ago(180),
    updatedAt: ago(150),
    message: 'Task completed successfully',
    meta: { durationMs: 45000 },
    result: {
      stdout: 'Performance optimization complete. Reduced bundle size by 12%.',
      stderr: '',
      truncated: false,
      exitCode: 0,
      durationMs: 45000,
    },
  },
  {
    id: 'task-005b-lint-fix',
    userId: 1,
    mode: 'implement',
    status: 'failed',
    internalStatus: 'timeout',
    branch: 'feature/lint-autofix',
    repoPath: '/app',
    createdAt: ago(200),
    updatedAt: ago(190),
    message: 'Task timed out after 300s',
    meta: { durationMs: 300000 },
    result: {
      stdout: 'Partial lint fixes applied before timeout.',
      stderr: 'Error: process killed after timeout',
      truncated: true,
      exitCode: 137,
      durationMs: 300000,
    },
  },
  {
    id: 'task-006-escalated',
    userId: 1,
    mode: 'review',
    status: 'escalated',
    internalStatus: 'escalated',
    branch: 'feature/payment-flow',
    repoPath: '/app',
    createdAt: ago(90),
    updatedAt: ago(60),
    message: 'Max review iterations reached',
    meta: { reviewIteration: 3, reviewMaxIterations: 3 },
    reviewFindings: 'Persistent security issue in payment handler',
    structuredFindings: [
      { id: 'F1', severity: 'critical', file: 'src/payment.ts', issue: 'No input validation on amount', risk: 'Financial loss', required_fix: 'Validate and sanitize amount input', acceptance_check: 'Negative and excessive amounts rejected' },
    ],
  },
]

export const mockEvents: Record<string, TaskEvent[]> = {
  'task-001-auth-refactor': [
    { id: 'evt-001', taskId: 'task-001-auth-refactor', status: 'claimed', phase: 'pull', message: 'Task claimed', meta: {}, createdAt: ago(30) },
    { id: 'evt-002', taskId: 'task-001-auth-refactor', status: 'started', phase: 'validate', message: 'Validating task', meta: {}, createdAt: ago(29) },
    { id: 'evt-003', taskId: 'task-001-auth-refactor', status: 'progress', phase: 'plan', message: 'Execution plan built', meta: { steps: ['validate', 'checkout', 'claude', 'report'] }, createdAt: ago(28) },
    { id: 'evt-004', taskId: 'task-001-auth-refactor', status: 'progress', phase: 'git', message: 'Checking out branch', meta: { stepIndex: 1, stepTotal: 4 }, createdAt: ago(27) },
    { id: 'evt-005', taskId: 'task-001-auth-refactor', status: 'progress', phase: 'claude', message: 'Claude subprocess spawned', meta: { stepIndex: 2, stepTotal: 4 }, createdAt: ago(2) },
  ],
}
